durga@48demo.com.bleadtest/src/objects/AttendeePaidHistory__c.object
<CustomObject>
    <label>AttendeePaidHistory</label>
    <nameField>
        <displayFormat>APH_{0000000}</displayFormat>
        <label>AttendeePaidHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeePaidHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/BL_Pricing__c.object
<CustomObject>
    <label>BL_Pricing</label>
    <nameField>
        <displayFormat>BLP_{00000000}</displayFormat>
        <label>BLP_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BL_Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/Booth_Qrcode__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event</relationshipLabel>
        <relationshipName>Booth_Qrcodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booth Qrcode</label>
    <nameField>
        <displayFormat>BQ-{0000}</displayFormat>
        <label>Booth Qrcode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth Qrcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/DeviceUsage__c.object
<CustomObject>
    <label>DeviceUsage</label>
    <nameField>
        <displayFormat>Dev_{000000000}</displayFormat>
        <label>DeviceUsage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeviceUsages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>TicketTypes__c</fullName>
        <description>Ticket Types used  to store the selected tickets by  Event Admin, used in the  Attendee registration</description>
        <inlineHelpText>Ticket Types used  to store the selected tickets by  Event Admin, used in the  Attendee registration</inlineHelpText>
        <label>TicketTypes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/Event_Invitee__c.object
<CustomObject>
    <label>Event_Invitee</label>
    <nameField>
        <displayFormat>EI_{0000000}</displayFormat>
        <label>EI_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Invitees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/EventSchedule__c.object
<CustomObject>
    <label>EventSchedule</label>
    <nameField>
        <displayFormat>ES_{00000000}</displayFormat>
        <label>ES_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventSchedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/Reports__c.object
<CustomObject>
    <label>Reports</label>
    <nameField>
        <displayFormat>RE_{00000000}</displayFormat>
        <label>RE_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/SecurityControls__c.object
<CustomObject>
    <label>SecurityControls</label>
    <nameField>
        <displayFormat>SC_{00000000}</displayFormat>
        <label>SC_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SecurityControls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/TicketTypes__c.object
<CustomObject>
    <label>TicketTypes</label>
    <nameField>
        <displayFormat>TT_{0000000}</displayFormat>
        <label>TT_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TicketTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/User_CheckinHistory__c.object
<CustomObject>
    <label>User_CheckinHistory</label>
    <nameField>
        <displayFormat>UC_{00000000}</displayFormat>
        <label>UC_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_CheckinHistory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/objects/User_Profile_Event__c.object
<CustomObject>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

durga@48demo.com.bleadtest/src/classes/clearDataBaseCon.cls
public with sharing class clearDataBaseCon {
 public string  s{get;set;}
 public string  p{get;set;}
 public string  q{get;set;}
    public String selected { get; set; }
public List<Sobject> listOfObjects{get;set;}
public  List<SelectOption> options {get;set;}
public clearDataBaseCon() {
s='BL_Pricing__c,Event__c,EventSchedule__c';

p ='Event_Attendee_Mapping__c';

q ='SecurityControls__c,User_CheckinHistory__c,User_Profile_Event__c,Reports__c,Event_Invitee__c,TicketTypes__c,AttendeePaidHistory__c,Booth_Qrcode__c,DeviceUsage__c';


}


public Pagereference clear(){

listOfObjects = new  List<Sobject>();
string [] po = new string[]{};
po=s.split(',');
for(string sl:po){
string cun ='select id from '+sl; 
listOfObjects = dataBase.query(cun);
system.debug('rrrrrrrrrrrr '+listOfObjects.size());
if(listOfObjects !=null){
delete listOfObjects;
listOfObjects  = new List<Sobject>();
}
}






for(string s3:q.split(',')){
string cun ='select id from '+s3; 
listOfObjects = dataBase.query(cun);
system.debug('rrrrrrrrrrrr '+listOfObjects.size());
if(listOfObjects !=null){
delete listOfObjects;
listOfObjects  = new List<Sobject>();
}
}




for(string s3:p.split(',')){
string cun ='select id from '+s3; 
listOfObjects = dataBase.query(cun);
system.debug('rrrrrrrrrrrr '+listOfObjects.size());
if(listOfObjects !=null){
delete listOfObjects;
listOfObjects  = new List<Sobject>();
}
}

return null;
}





}